<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE generatorConfiguration[
        <!ELEMENT generatorConfiguration (properties,generateFile+) >
        <!ELEMENT properties (property*) >
        <!ELEMENT property  EMPTY>
        <!ELEMENT attribute  EMPTY>
        <!ELEMENT list  (attribute+)>
        <!ELEMENT generateFile (property*,list*)>
        <!ATTLIST property
                name    CDATA #REQUIRED
                value   CDATA #REQUIRED >
        <!ATTLIST generateFile
                packagePath    CDATA #IMPLIED
                webPath    CDATA #IMPLIED
                templateName   CDATA #REQUIRED
                fileName   CDATA #REQUIRED>
        <!ATTLIST list
                name    CDATA #REQUIRED >

        <!ATTLIST attribute
                name    CDATA #REQUIRED
                value    CDATA #IMPLIED
                required CDATA #IMPLIED
                comment CDATA #IMPLIED
                display CDATA #IMPLIED
                >
        ]>

<generatorConfiguration>
    <!--全局属性-->
    <properties>
        <property name="servicePackage" value="com.little.g.test" />
        <property name="author" value="lengligang" />
    </properties>
    <!--全局属性-->
    <generateFile packagePath="/com/little/g/test" templateName="Service.tpl" fileName="TestService.java">
        <property name="topLevel" value="com.little.g" />
        <property name="tablecomment" value="这是测试" />
        <property name="classObjectName" value="哈哈" />
        <property name="className" value="className" />
    </generateFile>


    <generateFile webPath="/book" templateName="Service.tpl" fileName="Test.jsp">
        <property name="entityName" value="Book" />
        <list name="attributes">
            <attribute name="entityName"  required="true" comment="描述"  />
        </list>
    </generateFile>

</generatorConfiguration>